spring.application.name=helene
server.port=8080

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/helene_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
# PAYPAL
paypal.client-id=Ac8CkC6BpfCKEGVVlb8XRsup6AcTo3IckYoKPHCu4Y8Vlxmj251nM4Gj9x0rFswhOAzFEbqBhdEIS4W4
paypal.client-secret=ENqQ0GJIW4oLKygjSwdAlQnVXWR2jdNEt38tiGKC-ZWRqTeJNQ3nAFQlfiHOywq7XJcFXG_WPDi8CNJP
paypal.base-url=https://api-m.sandbox.paypal.com

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.default-models-expand-depth=-1

spring.jackson.serialization.write-dates-as-timestamps=false



spring.flyway.enabled=true
spring.flyway.repair-on-migrate=true
spring.flyway.locations=classpath:db/migration
